### PR TITLE
Add step to correctly configure go

### PR DESCRIPTION
**Pull request by nhhagen**
Closes: coopnorge/member-api#166

### CODE REVIEW

**Comment by nhhagen** [comment]
Tested in this PR: https://github.com/coopnorge/member-api/pull/169

**Comment by nhhagen** [comment]
The solution can be replicated for other languages with similar problems (I know we have some similar issues with java). It would be nice if we could read this from a configuration file that is not owner by the security guild.

**Comment by nhhagen** [comment]
After discussing offline with @aucampia we decided that setting a default version of golang is better than defaulting to what ever the current one in the GitHub Actions image is.

**Review by AtzeDeVries — APPROVED** [review]

**Review by aucampia — APPROVED** [review]
LGTM, go versions are backwards compatible, so using 1.19 with a codebase that is written for 1.17 should work fine. The only problems I have had is when using a later version in go.mod than is supported by linters, but that won't be impacted by this.

**Review by frankthing — APPROVED** [review]

**Pull request merged**
